export const INPUT_PROJECT_TITLE = "INPUT_PROJECT_TITLE";
export const INPUT_PROJECT_DESCRIPTION = "INPUT_PROJECT_DESCRIPTION";
export const INPUT_TASK_TITLE = "INPUT_TASK_TITLE";
export const INPUT_TASK_DESCRIPTION = "INPUT_TASK_DESCRIPTION";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const BEFORE_LOAD_PROJECTS = "BEFORE_LOAD_PROJECTS";
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const ADD_TASK = "ADD_TASK";

export const SHOW_TASKS = "SHOW_TASKS";
export const SHOW_IN_PROCESS = "SHOW_IN_PROCESS";
export const SHOW_DONE = "SHOW_DONE";
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_ADD_TASK = "SHOW_ADD_TASK";
export const HIDE_ADD_TASK = "HIDE_ADD_TASK";
