export const INPUT_PROJECT_TITLE = "INPUT_PROJECT_TITLE";
export const INPUT_PROJECT_DESCRIPTION = "INPUT_PROJECT_DESCRIPTION";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const BEFORE_LOAD_PROJECTS = "BEFORE_LOAD_PROJECTS";
export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const ADD_TASK = "ADD_TASK";
