export const INPUT_SIGNIN_USERNAME = "INPUT_SIGNIN_USERNAME";
export const INPUT_SIGNIN_PASSWORD = "INPUT_SIGNIN_PASSWORD";
export const INPUT_SIGNUP_USERNAME = "INPUT_SIGNUP_USERNAME";
export const INPUT_SIGNUP_PASSWORD = "INPUT_SIGNUP_PASSWORD";
export const INPUT_SIGNUP_REPEAT_PASSWORD = "INPUT_SIGNUP_REPEAT_PASSWORD";

export const SIGNIN = "SIGNIN";
export const SIGNUP = "SIGNUP";

export const CHECK_AUTH = "CHECK_AUTH";
